version: "3"
services:
  gnowdb:
    build: ./
    image: gnowdb:v1
    container_name: gnowdbc
    links:
      - neo4j:neo4jc
    ports:
      - 3000:3000
    volumes:
      - /tmp/gnowdb_data/gnowdb_settings:/root/gnowdb_settings
    #   - /tmp/gnowdb/data:/usr/src/app

  neo4j:
    image: neo4j:3.4.7-enterprise
    container_name: neo4jc
    ports:
      - 7473:7473           #https
      - 7474:7474           #http
      - 7687:7687           #bolt
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    # volumes:
    #   - /tmp/neo4j/data:/data